name: build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: nurdism/neko:dev
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow

    - name: Get go dependencies and build server
      working-directory: server
      run: |
        go get -v -t -d . 
        ./build

    - name: Get npm dependencies and build Client
      working-directory: client
      run: | 
        npm install
        npm run build